### PR TITLE
Add Muse proto

### LINKED ISSUE #1: Question: will this work with the Proto Muse board?
It looks perfect for replacing my Chromesast Audio.

### PR DESCRIPTION
**Pull request by balloob**
Add support for Muse Proto https://raspiaudio.com/produit/muse-proto

Fixes #1

### CODE REVIEW

**Comment by balloob** [comment]
Will merge this so you can try it out @tomlut, and will validate when mine comes in later today.

**Comment by tomlut** [comment]
Thanks Paulus. Mine's due to arrive in two weeks.

**Comment by balloob** [comment]
Yep it works 👍 

Screenshot of the logs after installing it:

image

**Comment by tomlut** [comment]
Nice!

**Comment by tomlut** [comment]
My Muse Proto arrived today. I flashed it with your handy tool and connected to teh proto access point. I logged into the device with a web browser and get it joined up to my network but that's all. 

I cant get Home Assistant to find it. 

My iPhone cant airplay to it (refuses to connect). 

And if I reboot it the muse proto seems to forget the network settings and falls back to its wifi access point.

Seems a bit of a dud.

**Pull request merged**
